# This workflow checks if the code complies with out .clang-format file
#
name: Check clang-format

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: 'src tests'
        # exclude: 'none'
        extensions: 'h,cpp'
        clangFormatVersion: 9
        style: file
